// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_3aN4Fno41kutRDP2IFixlxhL_qysrrg',
    appId: '1:618306678005:web:e92759951d49d05b28e9bc',
    messagingSenderId: '618306678005',
    projectId: 'study-app-882d8',
    authDomain: 'study-app-882d8.firebaseapp.com',
    storageBucket: 'study-app-882d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUslU259FdbEdhD5PWvz9aLNB0zeAack',
    appId: '1:618306678005:android:2cce5e6c1731cf2828e9bc',
    messagingSenderId: '618306678005',
    projectId: 'study-app-882d8',
    storageBucket: 'study-app-882d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZDkXuamyy8MU3VbHjX7c4saFJn1NwmKA',
    appId: '1:618306678005:ios:eea1cf3d837a869428e9bc',
    messagingSenderId: '618306678005',
    projectId: 'study-app-882d8',
    storageBucket: 'study-app-882d8.appspot.com',
    iosClientId: '618306678005-1unve0saqesv1bf63o6tpa5r0ht0nebs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZDkXuamyy8MU3VbHjX7c4saFJn1NwmKA',
    appId: '1:618306678005:ios:eea1cf3d837a869428e9bc',
    messagingSenderId: '618306678005',
    projectId: 'study-app-882d8',
    storageBucket: 'study-app-882d8.appspot.com',
    iosClientId: '618306678005-1unve0saqesv1bf63o6tpa5r0ht0nebs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseStudyApp',
  );
}
